
#Question 1 Part a

In [1]:
#importing packages...
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import classification_report,confusion_matrix
import pandas as pd
#importing dataset....
data_set=pd.read_csv("bank.csv",sep=';')
df=pd.DataFrame(data_set)
print(df)

      age            job   marital  education default  balance housing loan  \
0      30     unemployed   married    primary      no     1787      no   no   
1      33       services   married  secondary      no     4789     yes  yes   
2      35     management    single   tertiary      no     1350     yes   no   
3      30     management   married   tertiary      no     1476     yes  yes   
4      59    blue-collar   married  secondary      no        0     yes   no   
5      35     management    single   tertiary      no      747      no   no   
6      36  self-employed   married   tertiary      no      307     yes   no   
7      39     technician   married  secondary      no      147     yes   no   
8      41   entrepreneur   married   tertiary      no      221     yes   no   
9      43       services   married    primary      no      -88     yes  yes   
10     39       services   married  secondary      no     9374     yes   no   
11     43         admin.   married  secondary      n

In [2]:
print('A look at the data')
print(df.head(),'\n')

print ('Number of columns and rows of the data ')
print(df.shape,'\n')

print ('Description of the data')
print(df.describe(),'\n')

print ('Types of data values')
print(df.dtypes, '\n')

#identify nans
def num_missing(x):
    return sum(x.isnull())
#Applying per column:
print ("Missing values per column:")
print (df.apply(num_missing, axis=0),'\n') 

A look at the data
   age          job  marital  education default  balance housing loan  \
0   30   unemployed  married    primary      no     1787      no   no   
1   33     services  married  secondary      no     4789     yes  yes   
2   35   management   single   tertiary      no     1350     yes   no   
3   30   management  married   tertiary      no     1476     yes  yes   
4   59  blue-collar  married  secondary      no        0     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome   y  
0  cellular   19   oct        79         1     -1         0  unknown  no  
1  cellular   11   may       220         1    339         4  failure  no  
2  cellular   16   apr       185         1    330         1  failure  no  
3   unknown    3   jun       199         4     -1         0  unknown  no  
4   unknown    5   may       226         1     -1         0  unknown  no   

Number of columns and rows of the data 
(4521, 17) 

Description of the data
             

In [3]:
#Converting categorical values to numerical values using label encoder
le=LabelEncoder()
# Iterating over all the common columns in train and test
for col in df.columns.values:
       # Encoding only categorical variables
    if df[col].dtypes=='object':
       # Using whole data to form an exhaustive list of levels
        data=df[col].append(df[col])
        le.fit(data.values)
        df[col]=le.transform(df[col])
print(df)

      age  job  marital  education  default  balance  housing  loan  contact  \
0      30   10        1          0        0     1787        0     0        0   
1      33    7        1          1        0     4789        1     1        0   
2      35    4        2          2        0     1350        1     0        0   
3      30    4        1          2        0     1476        1     1        2   
4      59    1        1          1        0        0        1     0        2   
5      35    4        2          2        0      747        0     0        0   
6      36    6        1          2        0      307        1     0        0   
7      39    9        1          1        0      147        1     0        0   
8      41    2        1          2        0      221        1     0        2   
9      43    7        1          0        0      -88        1     1        0   
10     39    7        1          1        0     9374        1     0        2   
11     43    0        1          1      

In [4]:
#Seperating the target variable
array=df.values
#the dataset without the  column: 'y'
X=array[:,0:16]
print("X")
print(X)
#the target column: y
Y=array[:,16]
print("Y")
print(Y)

X
[[ 30  10   1 ...  -1   0   3]
 [ 33   7   1 ... 339   4   0]
 [ 35   4   2 ... 330   1   0]
 ...
 [ 57   9   1 ...  -1   0   3]
 [ 28   1   1 ... 211   3   1]
 [ 44   2   2 ... 249   7   1]]
Y
[0 0 0 ... 0 0 0]


In [5]:
#Splitting train and test data using stratified split
X_train, X_test, Y_train, Y_test = train_test_split(X , Y, test_size=0.3, random_state = 2000,stratify=Y)
#print(Y_test.shape)

In [6]:
#Applying standard scalar (Data is coverted so that mean=0 and SD=1)
scaler = StandardScaler()
scaler.fit(X_train)
scaler.fit(X_test)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [7]:
#Splitting data for training into training and validation sets
X_tr,X_val,Y_tr,Y_val= train_test_split(X_train,Y_train,test_size=0.2, random_state = 2000,shuffle=True)

In [8]:
#Different classifiers used..
classifiers = [
    KNeighborsClassifier(3),
    SVC(),
    DecisionTreeClassifier(),
    GaussianNB(),
    LinearDiscriminantAnalysis()]

In [9]:
print("***After training...***")
for clf in classifiers:
    clf.fit(X_tr,Y_tr)
    
    name = clf.__class__.__name__
    print("***",name,"***")
    predictions = clf.predict(X_val)
    #Train accuracy
    ac_tr=accuracy_score(Y_tr,clf.predict(X_tr))
    print("Training accuracy:",ac_tr*100,"%")
    #Validation accuracy
   
    ac_val=accuracy_score(Y_val, predictions)
    print("Validation score:",ac_val*100,"%")
    print(confusion_matrix(Y_val,predictions))
    print(classification_report(Y_val,predictions))

***After training...***
*** KNeighborsClassifier ***
Training accuracy: 92.80916633741604 %
Validation score: 86.57187993680886 %
[[534  19]
 [ 66  14]]
             precision    recall  f1-score   support

          0       0.89      0.97      0.93       553
          1       0.42      0.17      0.25        80

avg / total       0.83      0.87      0.84       633

*** SVC ***
Training accuracy: 91.54484393520347 %
Validation score: 87.51974723538704 %
[[545   8]
 [ 71   9]]
             precision    recall  f1-score   support

          0       0.88      0.99      0.93       553
          1       0.53      0.11      0.19        80

avg / total       0.84      0.88      0.84       633

*** DecisionTreeClassifier ***
Training accuracy: 100.0 %
Validation score: 84.67614533965245 %
[[502  51]
 [ 46  34]]
             precision    recall  f1-score   support

          0       0.92      0.91      0.91       553
          1       0.40      0.42      0.41        80

avg / total       0.85   

In [10]:
print("***After training...***")
for clf in classifiers:
    name = clf.__class__.__name__
    print("***",name,"***")
    predictions = clf.predict(X_test)

    ac_test=accuracy_score(Y_test, predictions)
    print("Testing accuracy:",ac_test*100,"%")
    print(confusion_matrix(Y_test,predictions))
    print(classification_report(Y_test,predictions))

***After training...***
*** KNeighborsClassifier ***
Testing accuracy: 89.240972733972 %
[[1171   30]
 [ 116   40]]
             precision    recall  f1-score   support

          0       0.91      0.98      0.94      1201
          1       0.57      0.26      0.35       156

avg / total       0.87      0.89      0.87      1357

*** SVC ***
Testing accuracy: 89.31466470154753 %
[[1184   17]
 [ 128   28]]
             precision    recall  f1-score   support

          0       0.90      0.99      0.94      1201
          1       0.62      0.18      0.28       156

avg / total       0.87      0.89      0.87      1357

*** DecisionTreeClassifier ***
Testing accuracy: 84.3036109064112 %
[[1074  127]
 [  86   70]]
             precision    recall  f1-score   support

          0       0.93      0.89      0.91      1201
          1       0.36      0.45      0.40       156

avg / total       0.86      0.84      0.85      1357

*** GaussianNB ***
Testing accuracy: 84.0825350036846 %
[[1066  135