Question 1 Part b

In [1]:
#importing packages...
import numpy as np
from sklearn.neural_network import MLPClassifier 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import classification_report,confusion_matrix
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
#importing dataset....
data_set=pd.read_csv("bc.csv")
df=pd.DataFrame(data_set)
# print(df)

In [2]:
print('A look at the data')
print(df.head(),'\n')

print ('Number of columns and rows of the data ')
print(df.shape,'\n')

print ('Description of the data')
print(df.describe(),'\n')

print ('Types of data values')
print(df.dtypes, '\n')

#identify nans
def num_missing(x):
    return sum(x.isnull())
#Applying per column:
print ("Missing values per column:")
print (df.apply(num_missing, axis=0),'\n') 

A look at the data
         id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

      ...       texture_worst  perimeter_wo

In [3]:
#Converting categorical values to numerical values using label encoder
le=LabelEncoder()
# Iterating over all the common columns in train and test
for col in df.columns.values:
       # Encoding only categorical variables
    if df[col].dtypes=='object':
       # Using whole data to form an exhaustive list of levels
        data=df[col].append(df[col])
        le.fit(data.values)
        df[col]=le.transform(df[col])
# print(df)

In [4]:
#Seperating the target variable
array=df.values
#the dataset without the  column: 'y'
X=array[:,2:32]
# print("X")
# print(X)
#the target column: y
Y=array[:,1]
# print("Y")
# print(Y)

In [5]:
#Splitting train and test data using stratified split
X_train, X_test, Y_train, Y_test = train_test_split(X , Y, test_size=0.3, random_state = 2000,stratify=Y)
#print(Y_test.shape)

In [6]:
#Applying standard scalar (Data is coverted so that mean=0 and SD=1)
scaler = StandardScaler()
scaler.fit(X_train)
scaler.fit(X_test)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
#Splitting data for training into training and validation sets
X_tr,X_val,Y_tr,Y_val= train_test_split(X_train,Y_train,test_size=0.2, random_state = 2000,shuffle=True)

In [1]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier().fit(X_tr, Y_tr)
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_tr, Y_tr)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_val, Y_val)))

NameError: name 'X_tr' is not defined

In [8]:
#Different classifiers used..
classifiers = [
    KNeighborsClassifier(3),
    SVC(),
    DecisionTreeClassifier(),
    GaussianNB(),
    LinearDiscriminantAnalysis()]

In [9]:
print("***After training...***")
for clf in classifiers:
    clf.fit(X_tr,Y_tr)
    
    name = clf.__class__.__name__
    print("***",name,"***")
    predictions = clf.predict(X_val)
    #Train accuracy
    ac_tr=accuracy_score(Y_tr,clf.predict(X_tr))
    print("Training accuracy:",ac_tr*100,"%")
    #Validation accuracy
   
    ac_val=accuracy_score(Y_val, predictions)
    print("Validation score:",ac_val*100,"%")
    print(confusion_matrix(Y_val,predictions))
    print(classification_report(Y_val,predictions))

***After training...***
*** KNeighborsClassifier ***
Training accuracy: 98.11320754716981 %
Validation score: 96.25 %
[[44  0]
 [ 3 33]]
             precision    recall  f1-score   support

        0.0       0.94      1.00      0.97        44
        1.0       1.00      0.92      0.96        36

avg / total       0.96      0.96      0.96        80

*** SVC ***
Training accuracy: 98.11320754716981 %
Validation score: 98.75 %
[[44  0]
 [ 1 35]]
             precision    recall  f1-score   support

        0.0       0.98      1.00      0.99        44
        1.0       1.00      0.97      0.99        36

avg / total       0.99      0.99      0.99        80

*** DecisionTreeClassifier ***
Training accuracy: 100.0 %
Validation score: 90.0 %
[[41  3]
 [ 5 31]]
             precision    recall  f1-score   support

        0.0       0.89      0.93      0.91        44
        1.0       0.91      0.86      0.89        36

avg / total       0.90      0.90      0.90        80

*** GaussianNB ***
T

In [10]:
print("***After training...***")
for clf in classifiers:
    name = clf.__class__.__name__
    print("***",name,"***")
    predictions = clf.predict(X_test)

    ac_test=accuracy_score(Y_test, predictions)
    print("Testing accuracy:",ac_test*100,"%")
    print(confusion_matrix(Y_test,predictions))
    print(classification_report(Y_test,predictions))

***After training...***
*** KNeighborsClassifier ***
Testing accuracy: 97.6608187134503 %
[[106   1]
 [  3  61]]
             precision    recall  f1-score   support

        0.0       0.97      0.99      0.98       107
        1.0       0.98      0.95      0.97        64

avg / total       0.98      0.98      0.98       171

*** SVC ***
Testing accuracy: 98.24561403508771 %
[[105   2]
 [  1  63]]
             precision    recall  f1-score   support

        0.0       0.99      0.98      0.99       107
        1.0       0.97      0.98      0.98        64

avg / total       0.98      0.98      0.98       171

*** DecisionTreeClassifier ***
Testing accuracy: 90.05847953216374 %
[[94 13]
 [ 4 60]]
             precision    recall  f1-score   support

        0.0       0.96      0.88      0.92       107
        1.0       0.82      0.94      0.88        64

avg / total       0.91      0.90      0.90       171

*** GaussianNB ***
Testing accuracy: 95.32163742690058 %
[[101   6]
 [  2  62]]
 